//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salvaviajes.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth
    {
        public int AuthId { get; set; }
        public int HumanitarianOrganizationId { get; set; }
        public string LoginName { get; set; }
        public byte[] Password { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public string Description { get; set; }
    }
}
