//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salvaviajes.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentary
    {
        public int DocumentaryId { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public Nullable<int> LikertScale { get; set; }
        public Nullable<int> UpVoteCounts { get; set; }
        public Nullable<int> RelatedDocumentaryId { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<System.DateTime> PublishedOn { get; set; }
        public Nullable<int> PublishedBy { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string ContentPath { get; set; }
    }
}
