//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salvaviajes.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanitarianOrganization
    {
        public HumanitarianOrganization()
        {
            this.Auths = new HashSet<Auth>();
        }
    
        public int HumanitarianOrganizationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual ICollection<Auth> Auths { get; set; }
        public virtual Location Location { get; set; }
    }
}
