//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salvaviajes.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journey
    {
        public Journey()
        {
            this.JourneyPaths = new HashSet<JourneyPath>();
        }
    
        public int JourneyId { get; set; }
        public Nullable<int> ActualOrginationId { get; set; }
        public Nullable<int> ActualDestinationId { get; set; }
        public Nullable<System.DateTime> ActualDepartureDate { get; set; }
        public Nullable<int> ActualDuration { get; set; }
        public Nullable<int> ActualNumberOfTravelers { get; set; }
        public Nullable<int> PlannedOrginationId { get; set; }
        public Nullable<int> PlannedDestinationId { get; set; }
        public Nullable<System.DateTime> PlannedDepartureDate { get; set; }
        public Nullable<int> PlannedDuration { get; set; }
        public Nullable<int> PlannedNumberOfTravelers { get; set; }
        public Nullable<int> DocumentaryId { get; set; }
    
        public virtual Location ActualOrigination { get; set; }
        public virtual Location ActualDestination { get; set; }
        public virtual Location PlannedOrigination { get; set; }
        public virtual Location PlannedDestination { get; set; }
        public virtual ICollection<JourneyPath> JourneyPaths { get; set; }
        public virtual Documentary Documentary { get; set; }
    }
}
