//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salvaviajes.Data.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalvaviajesEntities : DbContext
    {
        public SalvaviajesEntities()
            : base("name=SalvaviajesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SMSAidGroup> SMSAidGroups { get; set; }
        public DbSet<SMSCategory> SMSCategories { get; set; }
        public DbSet<SMSIssue> SMSIssues { get; set; }
        public DbSet<SMSErrorLog> SMSErrorLogs { get; set; }
        public DbSet<Auth> Auths { get; set; }
        public DbSet<Documentary> Documentaries { get; set; }
        public DbSet<HumanitarianOrganization> HumanitarianOrganizations { get; set; }
        public DbSet<Journey> Journeys { get; set; }
        public DbSet<JourneyPath> JourneyPaths { get; set; }
        public DbSet<Location> Locations { get; set; }
    }
}
