//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salvaviajes.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSIssue
    {
        public int IssueId { get; set; }
        public string SMSGuid { get; set; }
        public string ReportedFrom { get; set; }
        public System.DateTime ReportedOn { get; set; }
        public System.DateTime LoggedOn { get; set; }
        public string Description { get; set; }
        public Nullable<int> LikertScale { get; set; }
        public Nullable<int> UpVoteCounts { get; set; }
        public Nullable<int> ParentIssueId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> JourneyId { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
